// flow-typed signature: 2fc1a8e11254673aa974d5c9aa8f550a
// flow-typed version: <<STUB>>/easy-table_v^1.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'easy-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'easy-table' {
  declare type TableData = Array<{}>
  declare module.exports: {
    print(data: TableData): void
  }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'easy-table/table' {
  declare module.exports: any;
}

// Filename aliases
declare module 'easy-table/table.js' {
  declare module.exports: $Exports<'easy-table/table'>;
}
