// flow-typed signature: b7e527326f675d8c427a44123fe2c67f
// flow-typed version: <<STUB>>/prismic-javascript_v^1.1.4/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prismic-javascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prismic-javascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prismic-javascript/dist/prismic-javascript' {
  declare module.exports: any;
}

declare module 'prismic-javascript/dist/prismic-javascript.min' {
  declare module.exports: any;
}

declare module 'prismic-javascript/docs/assets/js/main' {
  declare module.exports: any;
}

declare module 'prismic-javascript/docs/assets/js/search' {
  declare module.exports: any;
}

declare module 'prismic-javascript/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prismic-javascript/dist/prismic-javascript.js' {
  declare module.exports: $Exports<'prismic-javascript/dist/prismic-javascript'>;
}
declare module 'prismic-javascript/dist/prismic-javascript.min.js' {
  declare module.exports: $Exports<'prismic-javascript/dist/prismic-javascript.min'>;
}
declare module 'prismic-javascript/docs/assets/js/main.js' {
  declare module.exports: $Exports<'prismic-javascript/docs/assets/js/main'>;
}
declare module 'prismic-javascript/docs/assets/js/search.js' {
  declare module.exports: $Exports<'prismic-javascript/docs/assets/js/search'>;
}
declare module 'prismic-javascript/webpack.config.js' {
  declare module.exports: $Exports<'prismic-javascript/webpack.config'>;
}
